---
title: "**Painel: COVID-19 no Brasil e no Mundo**"
output: 
  html_document:
    css: www/bootstrap.css
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r pacotes}
library(tidyverse)
library(readxl)
library(RCurl)
library(lubridate)
library(leaflet)
library(sf)
library(plotly)
library(DT)
library(shiny)
library(shinyalert)
library(progress)
library("rnaturalearth")
library("rnaturalearthdata")
library(geobr)
```

```{r carregar_funcoes, include = FALSE}
carregar_funcoes <- function(path) {
    folder_files <- list.files(path)
    dir_files <- paste0(path, folder_files)
    tryCatch({
        lapply(dir_files, source)
    }, error = function(e) {
        warning(paste("Nenhum arquivo encontrado em", path))
    })
}

carregar_funcoes("funcoes/")
```

```{r child = "analise_mundo.Rmd"}

```

```{r child = "analise_brasil.Rmd"}

```

```{r child = "analise_uf.Rmd"}

```


